# Generated by Django 3.2 on 2021-04-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senname', models.CharField(max_length=50)),
                ('recname', models.CharField(max_length=50)),
                ('senamt', models.IntegerField()),
                ('curbal', models.IntegerField()),
            ],
        ),
    ]
